export const AUDIT_ACTIONS = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_OTP_REQUESTED: "AUTH_OTP_REQUESTED",
  AUTH_OTP_VERIFIED: "AUTH_OTP_VERIFIED",
  AUTH_OTP_FAILED: "AUTH_OTP_FAILED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",
} as const;

export const AUDIT_RESOURCE_TYPES = {
  AUTHENTICATION: "AUTHENTICATION",
  USER: "USER",
  CUSTOMER: "CUSTOMER",
} as const;
